// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Calculator.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Calculator.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Calculator {

namespace {

const ::google::protobuf::Descriptor* Calculator_request_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Calculator_request_reflection_ = NULL;
const ::google::protobuf::Descriptor* Calculator_response_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Calculator_response_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* operation_type_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_Calculator_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_Calculator_2eproto() {
  protobuf_AddDesc_Calculator_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "Calculator.proto");
  GOOGLE_CHECK(file != NULL);
  Calculator_request_descriptor_ = file->message_type(0);
  static const int Calculator_request_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Calculator_request, operation_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Calculator_request, operand_a_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Calculator_request, operand_b_),
  };
  Calculator_request_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Calculator_request_descriptor_,
      Calculator_request::default_instance_,
      Calculator_request_offsets_,
      -1,
      -1,
      -1,
      sizeof(Calculator_request),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Calculator_request, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Calculator_request, _is_default_instance_));
  Calculator_response_descriptor_ = file->message_type(1);
  static const int Calculator_response_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Calculator_response, result_),
  };
  Calculator_response_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Calculator_response_descriptor_,
      Calculator_response::default_instance_,
      Calculator_response_offsets_,
      -1,
      -1,
      -1,
      sizeof(Calculator_response),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Calculator_response, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Calculator_response, _is_default_instance_));
  operation_type_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_Calculator_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Calculator_request_descriptor_, &Calculator_request::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Calculator_response_descriptor_, &Calculator_response::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_Calculator_2eproto() {
  delete Calculator_request::default_instance_;
  delete Calculator_request_reflection_;
  delete Calculator_response::default_instance_;
  delete Calculator_response_reflection_;
}

void protobuf_AddDesc_Calculator_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_Calculator_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020Calculator.proto\022\nCalculator\"i\n\022Calcul"
    "ator_request\022-\n\toperation\030\001 \001(\0162\032.Calcul"
    "ator.operation_type\022\021\n\toperand_a\030\002 \001(\002\022\021"
    "\n\toperand_b\030\003 \001(\002\"%\n\023Calculator_response"
    "\022\016\n\006result\030\001 \001(\002*W\n\016operation_type\022\007\n\003SU"
    "M\020\000\022\016\n\nDIFFERENCE\020\001\022\013\n\007PRODUCT\020\002\022\014\n\010DIVI"
    "SION\020\003\022\007\n\003POW\020\004\022\010\n\004SQRT\020\005b\006proto3", 273);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Calculator.proto", &protobuf_RegisterTypes);
  Calculator_request::default_instance_ = new Calculator_request();
  Calculator_response::default_instance_ = new Calculator_response();
  Calculator_request::default_instance_->InitAsDefaultInstance();
  Calculator_response::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_Calculator_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_Calculator_2eproto {
  StaticDescriptorInitializer_Calculator_2eproto() {
    protobuf_AddDesc_Calculator_2eproto();
  }
} static_descriptor_initializer_Calculator_2eproto_;
const ::google::protobuf::EnumDescriptor* operation_type_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return operation_type_descriptor_;
}
bool operation_type_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Calculator_request::kOperationFieldNumber;
const int Calculator_request::kOperandAFieldNumber;
const int Calculator_request::kOperandBFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Calculator_request::Calculator_request()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Calculator.Calculator_request)
}

void Calculator_request::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Calculator_request::Calculator_request(const Calculator_request& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Calculator.Calculator_request)
}

void Calculator_request::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  operation_ = 0;
  operand_a_ = 0;
  operand_b_ = 0;
}

Calculator_request::~Calculator_request() {
  // @@protoc_insertion_point(destructor:Calculator.Calculator_request)
  SharedDtor();
}

void Calculator_request::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Calculator_request::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Calculator_request::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Calculator_request_descriptor_;
}

const Calculator_request& Calculator_request::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Calculator_2eproto();
  return *default_instance_;
}

Calculator_request* Calculator_request::default_instance_ = NULL;

Calculator_request* Calculator_request::New(::google::protobuf::Arena* arena) const {
  Calculator_request* n = new Calculator_request;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Calculator_request::Clear() {
// @@protoc_insertion_point(message_clear_start:Calculator.Calculator_request)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(Calculator_request, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<Calculator_request*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(operation_, operand_b_);

#undef ZR_HELPER_
#undef ZR_

}

bool Calculator_request::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Calculator.Calculator_request)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .Calculator.operation_type operation = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_operation(static_cast< ::Calculator::operation_type >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(21)) goto parse_operand_a;
        break;
      }

      // optional float operand_a = 2;
      case 2: {
        if (tag == 21) {
         parse_operand_a:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &operand_a_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(29)) goto parse_operand_b;
        break;
      }

      // optional float operand_b = 3;
      case 3: {
        if (tag == 29) {
         parse_operand_b:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &operand_b_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Calculator.Calculator_request)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Calculator.Calculator_request)
  return false;
#undef DO_
}

void Calculator_request::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Calculator.Calculator_request)
  // optional .Calculator.operation_type operation = 1;
  if (this->operation() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->operation(), output);
  }

  // optional float operand_a = 2;
  if (this->operand_a() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->operand_a(), output);
  }

  // optional float operand_b = 3;
  if (this->operand_b() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->operand_b(), output);
  }

  // @@protoc_insertion_point(serialize_end:Calculator.Calculator_request)
}

::google::protobuf::uint8* Calculator_request::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Calculator.Calculator_request)
  // optional .Calculator.operation_type operation = 1;
  if (this->operation() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->operation(), target);
  }

  // optional float operand_a = 2;
  if (this->operand_a() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->operand_a(), target);
  }

  // optional float operand_b = 3;
  if (this->operand_b() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->operand_b(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Calculator.Calculator_request)
  return target;
}

int Calculator_request::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:Calculator.Calculator_request)
  int total_size = 0;

  // optional .Calculator.operation_type operation = 1;
  if (this->operation() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->operation());
  }

  // optional float operand_a = 2;
  if (this->operand_a() != 0) {
    total_size += 1 + 4;
  }

  // optional float operand_b = 3;
  if (this->operand_b() != 0) {
    total_size += 1 + 4;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Calculator_request::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Calculator.Calculator_request)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Calculator_request* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Calculator_request>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Calculator.Calculator_request)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Calculator.Calculator_request)
    MergeFrom(*source);
  }
}

void Calculator_request::MergeFrom(const Calculator_request& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Calculator.Calculator_request)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.operation() != 0) {
    set_operation(from.operation());
  }
  if (from.operand_a() != 0) {
    set_operand_a(from.operand_a());
  }
  if (from.operand_b() != 0) {
    set_operand_b(from.operand_b());
  }
}

void Calculator_request::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Calculator.Calculator_request)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Calculator_request::CopyFrom(const Calculator_request& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Calculator.Calculator_request)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Calculator_request::IsInitialized() const {

  return true;
}

void Calculator_request::Swap(Calculator_request* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Calculator_request::InternalSwap(Calculator_request* other) {
  std::swap(operation_, other->operation_);
  std::swap(operand_a_, other->operand_a_);
  std::swap(operand_b_, other->operand_b_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Calculator_request::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Calculator_request_descriptor_;
  metadata.reflection = Calculator_request_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Calculator_request

// optional .Calculator.operation_type operation = 1;
void Calculator_request::clear_operation() {
  operation_ = 0;
}
 ::Calculator::operation_type Calculator_request::operation() const {
  // @@protoc_insertion_point(field_get:Calculator.Calculator_request.operation)
  return static_cast< ::Calculator::operation_type >(operation_);
}
 void Calculator_request::set_operation(::Calculator::operation_type value) {
  
  operation_ = value;
  // @@protoc_insertion_point(field_set:Calculator.Calculator_request.operation)
}

// optional float operand_a = 2;
void Calculator_request::clear_operand_a() {
  operand_a_ = 0;
}
 float Calculator_request::operand_a() const {
  // @@protoc_insertion_point(field_get:Calculator.Calculator_request.operand_a)
  return operand_a_;
}
 void Calculator_request::set_operand_a(float value) {
  
  operand_a_ = value;
  // @@protoc_insertion_point(field_set:Calculator.Calculator_request.operand_a)
}

// optional float operand_b = 3;
void Calculator_request::clear_operand_b() {
  operand_b_ = 0;
}
 float Calculator_request::operand_b() const {
  // @@protoc_insertion_point(field_get:Calculator.Calculator_request.operand_b)
  return operand_b_;
}
 void Calculator_request::set_operand_b(float value) {
  
  operand_b_ = value;
  // @@protoc_insertion_point(field_set:Calculator.Calculator_request.operand_b)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Calculator_response::kResultFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Calculator_response::Calculator_response()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Calculator.Calculator_response)
}

void Calculator_response::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Calculator_response::Calculator_response(const Calculator_response& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Calculator.Calculator_response)
}

void Calculator_response::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  result_ = 0;
}

Calculator_response::~Calculator_response() {
  // @@protoc_insertion_point(destructor:Calculator.Calculator_response)
  SharedDtor();
}

void Calculator_response::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Calculator_response::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Calculator_response::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Calculator_response_descriptor_;
}

const Calculator_response& Calculator_response::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Calculator_2eproto();
  return *default_instance_;
}

Calculator_response* Calculator_response::default_instance_ = NULL;

Calculator_response* Calculator_response::New(::google::protobuf::Arena* arena) const {
  Calculator_response* n = new Calculator_response;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Calculator_response::Clear() {
// @@protoc_insertion_point(message_clear_start:Calculator.Calculator_response)
  result_ = 0;
}

bool Calculator_response::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Calculator.Calculator_response)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional float result = 1;
      case 1: {
        if (tag == 13) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &result_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Calculator.Calculator_response)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Calculator.Calculator_response)
  return false;
#undef DO_
}

void Calculator_response::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Calculator.Calculator_response)
  // optional float result = 1;
  if (this->result() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->result(), output);
  }

  // @@protoc_insertion_point(serialize_end:Calculator.Calculator_response)
}

::google::protobuf::uint8* Calculator_response::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Calculator.Calculator_response)
  // optional float result = 1;
  if (this->result() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->result(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Calculator.Calculator_response)
  return target;
}

int Calculator_response::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:Calculator.Calculator_response)
  int total_size = 0;

  // optional float result = 1;
  if (this->result() != 0) {
    total_size += 1 + 4;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Calculator_response::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Calculator.Calculator_response)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Calculator_response* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Calculator_response>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Calculator.Calculator_response)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Calculator.Calculator_response)
    MergeFrom(*source);
  }
}

void Calculator_response::MergeFrom(const Calculator_response& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Calculator.Calculator_response)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.result() != 0) {
    set_result(from.result());
  }
}

void Calculator_response::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Calculator.Calculator_response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Calculator_response::CopyFrom(const Calculator_response& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Calculator.Calculator_response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Calculator_response::IsInitialized() const {

  return true;
}

void Calculator_response::Swap(Calculator_response* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Calculator_response::InternalSwap(Calculator_response* other) {
  std::swap(result_, other->result_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Calculator_response::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Calculator_response_descriptor_;
  metadata.reflection = Calculator_response_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Calculator_response

// optional float result = 1;
void Calculator_response::clear_result() {
  result_ = 0;
}
 float Calculator_response::result() const {
  // @@protoc_insertion_point(field_get:Calculator.Calculator_response.result)
  return result_;
}
 void Calculator_response::set_result(float value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:Calculator.Calculator_response.result)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace Calculator

// @@protoc_insertion_point(global_scope)
